### ISSUE TITLE
Version bump for supporting node 0.11.

### ISSUE THREAD

**Issue by mzgoddard** [RReverser/when-traverse#4]
A version bump would be great so that node 11 users don't need to point to the github url in their package.json.

Thanks!

**Comment by mzgoddard** [comment]
To be a little more clear I mean it be great to see a release with my small fix for node 11 to be published on npm, I'd guess `2.1.3` but maybe you think it's worthy of being `2.2.0`.

**Comment by RReverser** [comment]
Done, thanks for the reminder (published as 2.1.3 since it's just a backward-compatible fix and not an API change).
