### ISSUE TITLE
this.into(new Promise) doesn't work?

### ISSUE THREAD

**Issue by braco** [RReverser/when-traverse#5]
Am I correct in thinking that

```
this.into(new Promise())
```

doesn't work? ie, that you can't supply a bare Promise instead of an object with mixed promise/values?

I see this listed in the documentation, but it doesn't seem to work from my tests.

**Comment by RReverser** [comment]
Yeah, `into` is specifically for traversing objects, otherwise you can use Promise as-is.

**Comment by braco** [comment]
Fixed when I used enter:, thanks
